services:
  web-single:
    build:
      context: ./nginx
      dockerfile: Dockerfile.web
    container_name: nginx-web
    ports:
      - "8081:80"

  web-multi:
    image: nginx:1.29.5-alpine
    container_name: nginx-multi
    ports:
      - "8082:81"
      - "8083:82"
      - "8084:83"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/simple-webpage:/usr/share/nginx/html/simple-webpage
      - ./nginx/html-arcade:/usr/share/nginx/html/html-arcade
      - ./nginx/simple-web-react:/usr/share/nginx/html/simple-web-react

  web-react:
    build:
      context: ./nginx
    container_name: nginx-react
    ports:
      - "8085:80"
    volumes:
      - ./nginx/react-ts/events.json:/usr/share/nginx/html/public/events.json:ro